import type { SerpApiClient as SerpApiClientContract, SerpApiSearchParameters } from './types.js'

export class MockSerpApiClient implements SerpApiClientContract {
  async search(parameters: SerpApiSearchParameters): Promise<unknown> {
    const query = String(parameters.q ?? '')
    return {
      organic_results: [
        {
          title: `Mock search result for ${query}`,
          link: 'https://example.com/mock-search-result',
          snippet: 'This result was generated by the local SerpApi mock client.',
        },
      ],
    }
  }
}