import type { SerpApiClient as SerpApiClientContract, SerpApiSearchParameters } from './types.js'

export class MockSerpApiClient implements SerpApiClientContract {
  async search(parameters: SerpApiSearchParameters): Promise<unknown> {
    const query = String(parameters.q ?? '')
    if (parameters.engine === 'google_maps') {
      return {
        local_results: [
          {
            title: `Mock place for ${query}`,
            address: '100 Example Street',
            rating: 4.5,
            reviews: 23,
            gps_coordinates: { latitude: 45.5231, longitude: -122.6765 },
            link: 'https://maps.google.com/?cid=mock-place',
          },
        ],
      }
    }

    if (parameters.engine === 'google_flights') {
      return {
        best_flights: [{
          flights: [{
            airline: 'Mock Air',
            flight_number: 'MA 101',
            departure_airport: { time: `${parameters.outbound_date} 09:00` },
            arrival_airport: { time: `${parameters.outbound_date} 12:00` },
            duration: 180,
          }],
          total_duration: 180,
          layovers: [],
          price: 250,
        }],
      }
    }

    if (parameters.engine === 'google_hotels') {
      return {
        properties: [{
          name: `Mock Hotel in ${String(parameters.q ?? '')}`,
          rate_per_night: { extracted_lowest: 125, lowest: '$125' },
          overall_rating: 4.4,
          reviews: 86,
          address: '200 Example Avenue',
          amenities: ['Free Wi-Fi', 'Air conditioning'],
          link: 'https://www.google.com/travel/search?q=mock-hotel',
        }],
      }
    }

    return {
      organic_results: [
        {
          title: `Mock search result for ${query}`,
          link: 'https://example.com/mock-search-result',
          snippet: 'This result was generated by the local SerpApi mock client.',
        },
      ],
    }
  }
}